### ISSUE TITLE
PROBLEMA 1 NO RESUELTO

### ISSUE THREAD

**Issue by nicomagno0** [jibericua/Wordle#2]
Cerraron el primer Issue SIN RESOLVERLO, NO HICIERON CAMBIOS AL RESPECTO. #1
![xyiq9rwkgag81](https://user-images.githubusercontent.com/103133102/165552718-46bd4f88-07a3-4b9f-b8fe-e3c00d9beda0.gif)

**Comment by nicomagno0** [comment]
Traten de no cerrar esto sin cambiar las direcciones de los archivos referentes a sus documentos de las palabras. 
![pato-que-dança-goose](https://user-images.githubusercontent.com/103133102/165553423-206a4a05-5c46-4a0c-85d7-423d5b71bf3d.gif)
![thanos-not-sure](https://user-images.githubusercontent.com/103133102/165553532-b0ade510-245c-4641-b373-454aeff52b12.gif)
Suerte y salu2.

**Comment by jibericua** [comment]
Ayer lo intente resolver pero no me di cuenta el problema era que al descargar el .rar se te descargar como wordle-main.py, ahi lo arregle. Apenas puedas fijate de descargar el .rar y probar que ande.
